# Generated by Django 5.0.7 on 2024-07-15 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=100)),
                ('title_eng', models.CharField(max_length=50)),
                ('poster_url', models.TextField(default='')),
                ('genre', models.CharField(max_length=30)),
                ('showtime', models.CharField(max_length=4)),
                ('release_date', models.CharField(max_length=15)),
                ('plot', models.TextField(default='')),
                ('rating', models.CharField(max_length=10)),
                ('director_name', models.CharField(max_length=30)),
                ('director_image_url', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('character', models.CharField(max_length=30)),
                ('image_url', models.TextField(default='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='mainpage.movie')),
            ],
        ),
    ]
