# Generated by Django 5.0.7 on 2024-07-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image_url',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director_image_url',
            field=models.TextField(default='', null=True),
        ),
    ]
