# Generated by Django 5.0.7 on 2024-07-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
